/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubhacks1;

/**
 *
 * @author siyuk
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        F2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        F3 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        F4 = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(190, 130, 130, 20);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(190, 170, 130, 22);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 130, 90, 16);

        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 170, 80, 16);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setText("Up for Grabs");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 80, 210, 40);

        jButton1.setText("Create Account");
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 270, 140, 40);

        jButton2.setText("Login");
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 270, 160, 40);

        javax.swing.GroupLayout F1Layout = new javax.swing.GroupLayout(F1.getContentPane());
        F1.getContentPane().setLayout(F1Layout);
        F1Layout.setHorizontalGroup(
            F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        F1Layout.setVerticalGroup(
            F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        F2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Create Account");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 40, 120, 50);

        jLabel5.setText("Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 100, 33, 16);

        jLabel6.setText("Age");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 140, 41, 16);

        jLabel7.setText("Gender(M/F/O)");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(260, 130, 110, 30);

        jLabel8.setText("Phone Number");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 180, 110, 16);

        jLabel9.setText("Brief Description");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 210, 120, 16);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 100, 280, 22);

        jTextField2.setText(" ");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 140, 69, 22);

        jTextField3.setText(" ");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(370, 140, 50, 22);

        jTextField4.setText(" ");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(190, 180, 230, 22);

        jTextField5.setText(" ");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 210, 230, 80);

        jButton3.setText("Cancel");
        jPanel2.add(jButton3);
        jButton3.setBounds(90, 320, 71, 25);

        jButton4.setText("Create my Account");
        jPanel2.add(jButton4);
        jButton4.setBounds(320, 320, 160, 25);

        javax.swing.GroupLayout F2Layout = new javax.swing.GroupLayout(F2.getContentPane());
        F2.getContentPane().setLayout(F2Layout);
        F2Layout.setHorizontalGroup(
            F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        F2Layout.setVerticalGroup(
            F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        jTextField6.setText(" ");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(40, 10, 420, 30);

        jButton5.setText("*");
        jPanel3.add(jButton5);
        jButton5.setBounds(10, 10, 30, 30);

        jButton6.setText("Search");
        jPanel3.add(jButton6);
        jButton6.setBounds(460, 10, 140, 30);

        jPanel4.setLayout(null);

        jLabel11.setText(" ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 10, 130, 160);

        jLabel10.setText(" ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 190, 130, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(270, 60, 130, 240);
        jPanel3.add(jScrollBar1);
        jScrollBar1.setBounds(570, 50, 21, 280);

        jPanel5.setLayout(null);

        jLabel13.setText(" ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 10, 130, 160);

        jLabel14.setText(" ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 190, 130, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(420, 60, 130, 240);

        jPanel6.setLayout(null);

        jLabel15.setText(" ");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 10, 110, 160);

        jLabel16.setText(" ");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, 190, 130, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(120, 60, 130, 240);

        jButton7.setText("Account");
        jPanel3.add(jButton7);
        jButton7.setBounds(10, 250, 100, 80);

        jButton8.setText("History");
        jPanel3.add(jButton8);
        jButton8.setBounds(10, 70, 100, 80);

        jButton9.setText("Notification");
        jPanel3.add(jButton9);
        jButton9.setBounds(10, 160, 100, 80);

        jButton20.setText("Write a post...");
        jPanel3.add(jButton20);
        jButton20.setBounds(30, 370, 570, 50);

        javax.swing.GroupLayout F3Layout = new javax.swing.GroupLayout(F3.getContentPane());
        F3.getContentPane().setLayout(F3Layout);
        F3Layout.setHorizontalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        F3Layout.setVerticalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setLayout(null);

        jTextField8.setText(" ");
        jPanel11.add(jTextField8);
        jTextField8.setBounds(40, 10, 420, 30);

        jButton15.setText("*");
        jPanel11.add(jButton15);
        jButton15.setBounds(10, 10, 30, 30);

        jButton16.setText("Search");
        jPanel11.add(jButton16);
        jButton16.setBounds(460, 10, 140, 30);

        jPanel12.setLayout(null);

        jLabel22.setText(" ");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(10, 10, 130, 160);

        jLabel23.setText(" ");
        jPanel12.add(jLabel23);
        jLabel23.setBounds(10, 190, 130, 40);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(270, 60, 130, 240);
        jPanel11.add(jScrollBar3);
        jScrollBar3.setBounds(570, 50, 21, 280);

        jPanel13.setLayout(null);

        jLabel24.setText(" ");
        jPanel13.add(jLabel24);
        jLabel24.setBounds(10, 10, 130, 160);

        jLabel25.setText(" ");
        jPanel13.add(jLabel25);
        jLabel25.setBounds(10, 190, 130, 40);

        jPanel11.add(jPanel13);
        jPanel13.setBounds(420, 60, 130, 240);

        jPanel14.setLayout(null);

        jLabel26.setText(" ");
        jPanel14.add(jLabel26);
        jLabel26.setBounds(10, 10, 110, 160);

        jLabel27.setText(" ");
        jPanel14.add(jLabel27);
        jLabel27.setBounds(0, 190, 130, 40);

        jPanel11.add(jPanel14);
        jPanel14.setBounds(120, 60, 130, 240);

        jButton17.setText("Account");
        jPanel11.add(jButton17);
        jButton17.setBounds(10, 250, 100, 80);

        jButton18.setText("History");
        jPanel11.add(jButton18);
        jButton18.setBounds(10, 70, 100, 80);

        jButton19.setText("Notification");
        jPanel11.add(jButton19);
        jButton19.setBounds(10, 160, 100, 80);

        javax.swing.GroupLayout F4Layout = new javax.swing.GroupLayout(F4.getContentPane());
        F4.getContentPane().setLayout(F4Layout);
        F4Layout.setHorizontalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        F4Layout.setVerticalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton21.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton21)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jButton21)
                .addGap(187, 187, 187))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame F1;
    private javax.swing.JFrame F2;
    private javax.swing.JFrame F3;
    private javax.swing.JFrame F4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
