
//
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.Date;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package class dubhacks1 {}

/**
 *
 * @author siyuk
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        f2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        f3 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        f4 = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        f5 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        uploadAPicture = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        f6 = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        PicofFood = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        f7 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        fA = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jButton37 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel66 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        fN = new javax.swing.JFrame();
        jPanel17 = new javax.swing.JPanel();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        Foodpic1 = new javax.swing.JLabel();
        Nameofevent = new javax.swing.JLabel();
        dropoutbutton = new javax.swing.JButton();
        jScrollBar2 = new javax.swing.JScrollBar();
        jPanel19 = new javax.swing.JPanel();
        Foodpic2 = new javax.swing.JLabel();
        Nameofevent1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        dropoutbutton1 = new javax.swing.JButton();
        timeforevent1 = new javax.swing.JLabel();
        addressforevent1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        Foodpic3 = new javax.swing.JLabel();
        Nameofevent2 = new javax.swing.JLabel();
        dropoutbutton2 = new javax.swing.JButton();
        fhN = new javax.swing.JFrame();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        requestername = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        genderfhN = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(320, 170, 230, 20);
        jPanel1.add(p1);
        p1.setBounds(320, 230, 230, 20);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 170, 90, 14);

        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 240, 80, 14);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setText("Up for Grabs");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 90, 210, 40);

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 400, 140, 40);

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 410, 160, 40);

        javax.swing.GroupLayout f1Layout = new javax.swing.GroupLayout(f1.getContentPane());
        f1.getContentPane().setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        f2.setBackground(new java.awt.Color(255, 255, 204));
        f2.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Create Account");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 40, 120, 50);

        jLabel5.setText("Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 100, 27, 14);

        jLabel6.setText("Birthday");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 140, 70, 14);

        jLabel7.setText("Gender(M/F/O)");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(440, 130, 110, 30);

        jLabel8.setText("Phone Number");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 180, 110, 14);

        jLabel9.setText("Brief Description");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 210, 120, 14);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 100, 570, 20);

        jTextField4.setText(" ");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(190, 180, 520, 20);

        jTextField5.setText(" ");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 220, 520, 170);

        jButton3.setText("Cancel");
        jPanel2.add(jButton3);
        jButton3.setBounds(90, 420, 65, 23);

        jButton4.setText("Create my Account");
        jPanel2.add(jButton4);
        jButton4.setBounds(580, 420, 160, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(540, 140, 64, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(150, 140, 45, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(230, 140, 37, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(310, 140, 49, 20);

        javax.swing.GroupLayout f2Layout = new javax.swing.GroupLayout(f2.getContentPane());
        f2.getContentPane().setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        jTextField6.setText(" ");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(40, 10, 600, 30);

        jButton6.setText("Search");
        jPanel3.add(jButton6);
        jButton6.setBounds(640, 10, 140, 30);

        jPanel4.setLayout(null);

        jLabel11.setText(" ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 10, 130, 160);

        jLabel10.setText(" ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 190, 130, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(340, 60, 170, 310);
<<<<<<< HEAD
        jPanel3.add(jScrollBar1);
        jScrollBar1.setBounds(750, 50, 17, 360);
=======
>>>>>>> origin/master

        jPanel5.setLayout(null);

        jLabel13.setText(" ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(30, 30, 130, 160);

        jLabel14.setText(" ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(30, 230, 130, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(530, 60, 180, 310);

        jPanel6.setLayout(null);

        jLabel15.setText(" ");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 10, 110, 160);

        jLabel16.setText(" ");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, 190, 130, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(130, 60, 180, 310);

        jButton7.setText("Account");
        jPanel3.add(jButton7);
        jButton7.setBounds(10, 280, 100, 80);

        jButton8.setText("Home");
        jPanel3.add(jButton8);
        jButton8.setBounds(10, 70, 100, 80);

        jButton9.setText("Notification");
        jPanel3.add(jButton9);
        jButton9.setBounds(10, 180, 100, 80);

        jButton20.setText("Write a post...");
        jPanel3.add(jButton20);
        jButton20.setBounds(90, 420, 670, 60);

        jLayeredPane1.setLayer(jScrollBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(607, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jPanel3.add(jLayeredPane1);
        jLayeredPane1.setBounds(130, 60, 640, 310);

        javax.swing.GroupLayout f3Layout = new javax.swing.GroupLayout(f3.getContentPane());
        f3.getContentPane().setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setLayout(null);

        jTextField8.setText(" ");
        jPanel11.add(jTextField8);
        jTextField8.setBounds(40, 20, 570, 30);

        jButton16.setText("Search");
        jPanel11.add(jButton16);
        jButton16.setBounds(610, 20, 140, 30);

        jPanel12.setLayout(null);

        jLabel22.setText(" ");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(10, 10, 130, 160);

        jLabel23.setText(" ");
        jPanel12.add(jLabel23);
        jLabel23.setBounds(10, 190, 130, 40);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(330, 60, 170, 310);
        jPanel11.add(jScrollBar3);
        jScrollBar3.setBounds(730, 60, 20, 330);

        jPanel13.setLayout(null);

        jLabel24.setText(" ");
        jPanel13.add(jLabel24);
        jLabel24.setBounds(10, 10, 130, 160);

        jLabel25.setText(" ");
        jPanel13.add(jLabel25);
        jLabel25.setBounds(10, 190, 130, 40);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel13.add(jLayeredPane2);
        jLayeredPane2.setBounds(-410, -10, 630, 330);

        jPanel11.add(jPanel13);
        jPanel13.setBounds(530, 70, 180, 310);

        jPanel14.setLayout(null);

        jLabel26.setText(" ");
        jPanel14.add(jLabel26);
        jLabel26.setBounds(10, 10, 110, 160);

        jLabel27.setText(" ");
        jPanel14.add(jLabel27);
        jLabel27.setBounds(0, 190, 130, 40);

        jPanel11.add(jPanel14);
        jPanel14.setBounds(120, 60, 170, 320);

        jButton17.setText("Account");
        jPanel11.add(jButton17);
        jButton17.setBounds(10, 300, 100, 80);

        jButton18.setText("Home");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton18);
        jButton18.setBounds(10, 70, 100, 80);

        jButton19.setText("Notification");
        jPanel11.add(jButton19);
        jButton19.setBounds(10, 180, 100, 80);

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4.getContentPane());
        f4.getContentPane().setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setLayout(null);

        jButton12.setText("Home");
        jPanel7.add(jButton12);
        jButton12.setBounds(10, 70, 100, 80);

        jButton13.setText("Notification");
        jPanel7.add(jButton13);
        jButton13.setBounds(10, 160, 100, 80);

        jButton14.setText("Account");
        jPanel7.add(jButton14);
        jButton14.setBounds(10, 250, 100, 80);

        jTextField9.setText("Write a description...");
        jPanel7.add(jTextField9);
        jTextField9.setBounds(140, 70, 660, 90);

        uploadAPicture.setText("Upload a picture");
        jPanel7.add(uploadAPicture);
        uploadAPicture.setBounds(140, 170, 240, 23);

        jLabel12.setText("Time Range: From");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(140, 210, 120, 14);

        jLabel17.setText("to");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(530, 210, 48, 14);

        jCheckBox1.setText("p.m.");
        jPanel7.add(jCheckBox1);
        jCheckBox1.setBounds(750, 240, 60, 23);

        jCheckBox2.setText("a.m.");
        jPanel7.add(jCheckBox2);
        jCheckBox2.setBounds(460, 210, 60, 23);

        jCheckBox3.setText("a.m.");
        jPanel7.add(jCheckBox3);
        jCheckBox3.setBounds(750, 210, 60, 23);

        jCheckBox4.setText("p.m.");
        jPanel7.add(jCheckBox4);
        jCheckBox4.setBounds(460, 240, 60, 23);
        jPanel7.add(jTextField10);
        jTextField10.setBounds(400, 210, 50, 20);
        jPanel7.add(jTextField11);
        jTextField11.setBounds(700, 210, 50, 20);

        jLabel18.setText("Number of Servings(Interger only):");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(140, 330, 230, 14);

        jTextField12.setText(" ");
        jPanel7.add(jTextField12);
        jTextField12.setBounds(360, 330, 9, 20);

        jLabel19.setText("Price [You don't have to charge people :)] : $");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(140, 370, 300, 14);

        jTextField13.setText(" ");
        jPanel7.add(jTextField13);
        jTextField13.setBounds(410, 370, 30, 20);

        jLabel20.setText("per serving");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(450, 370, 110, 14);

        jButton22.setText("Post");
        jPanel7.add(jButton22);
        jButton22.setBounds(620, 420, 140, 40);

        jButton23.setText("Cancel");
        jPanel7.add(jButton23);
        jButton23.setBounds(90, 410, 130, 40);

        jTextField14.setText("MM/DD/YYYY");
        jPanel7.add(jTextField14);
        jTextField14.setBounds(570, 210, 110, 20);

        jTextField15.setText("MM/DD/YYYY");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField15);
        jTextField15.setBounds(260, 210, 110, 20);

        javax.swing.GroupLayout f5Layout = new javax.swing.GroupLayout(f5.getContentPane());
        f5.getContentPane().setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setLayout(null);

        jButton24.setText("Account");
        jPanel8.add(jButton24);
        jButton24.setBounds(10, 250, 100, 80);

        jButton25.setText("Notification");
        jPanel8.add(jButton25);
        jButton25.setBounds(10, 160, 100, 80);

        jButton26.setText("Home");
        jPanel8.add(jButton26);
        jButton26.setBounds(10, 70, 100, 80);

        jLabel33.setText(" ");

        javax.swing.GroupLayout PicofFoodLayout = new javax.swing.GroupLayout(PicofFood);
        PicofFood.setLayout(PicofFoodLayout);
        PicofFoodLayout.setHorizontalGroup(
            PicofFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        PicofFoodLayout.setVerticalGroup(
            PicofFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel8.add(PicofFood);
        PicofFood.setBounds(150, 60, 240, 170);

        jLabel21.setText("Time Range: From");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(140, 250, 120, 14);

        jLabel28.setText("to");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(530, 250, 48, 14);

        jLabel29.setText("Number of unclaimed Servings:");
        jPanel8.add(jLabel29);
        jLabel29.setBounds(140, 360, 180, 14);

        jLabel30.setText("Price : $");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(140, 400, 300, 14);

        jLabel31.setText("/");
        jPanel8.add(jLabel31);
        jLabel31.setBounds(380, 360, 10, 14);

        jLabel32.setText(" ");
        jPanel8.add(jLabel32);
        jLabel32.setBounds(400, 360, 110, 30);

        jLabel34.setText(" ");
        jPanel8.add(jLabel34);
        jLabel34.setBounds(260, 240, 240, 40);

        jLabel35.setText(" ");
        jPanel8.add(jLabel35);
        jLabel35.setBounds(560, 240, 240, 50);

        jLabel36.setText(" ");
        jPanel8.add(jLabel36);
        jLabel36.setBounds(330, 360, 3, 14);

        jLabel37.setText(" ");
        jPanel8.add(jLabel37);
        jLabel37.setBounds(420, 400, 3, 14);

        jButton30.setText("Delete This Post");
        jPanel8.add(jButton30);
        jButton30.setBounds(540, 420, 220, 50);
        jPanel8.add(jLabel38);
        jLabel38.setBounds(470, 70, 0, 0);

        jLabel39.setText(" ");
        jPanel8.add(jLabel39);
        jLabel39.setBounds(430, 80, 300, 110);

        jLabel40.setText(" ");
        jPanel8.add(jLabel40);
        jLabel40.setBounds(330, 360, 50, 30);

        jLabel41.setText(" ");
        jPanel8.add(jLabel41);
        jLabel41.setBounds(420, 390, 100, 60);

        javax.swing.GroupLayout f6Layout = new javax.swing.GroupLayout(f6.getContentPane());
        f6.getContentPane().setLayout(f6Layout);
        f6Layout.setHorizontalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );
        f6Layout.setVerticalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setLayout(null);

        jButton28.setText("Notification");
        jPanel9.add(jButton28);
        jButton28.setBounds(10, 160, 100, 80);

        jButton29.setText("Account");
        jPanel9.add(jButton29);
        jButton29.setBounds(10, 250, 100, 80);

        jButton31.setText("Home");
        jPanel9.add(jButton31);
        jButton31.setBounds(10, 70, 100, 80);

        jLabel43.setText("Time Range: From");
        jPanel9.add(jLabel43);
        jLabel43.setBounds(140, 250, 120, 14);

        jLabel44.setText(" ");
        jPanel9.add(jLabel44);
        jLabel44.setBounds(260, 240, 240, 40);

        jLabel46.setText("to");
        jPanel9.add(jLabel46);
        jLabel46.setBounds(530, 250, 48, 14);

        jLabel45.setText(" ");
        jPanel9.add(jLabel45);
        jLabel45.setBounds(410, 60, 300, 110);

        jLabel47.setText(" ");
        jPanel9.add(jLabel47);
        jLabel47.setBounds(560, 240, 240, 50);

        jLabel48.setText("Number of unclaimed Servings:");
        jPanel9.add(jLabel48);
        jLabel48.setBounds(140, 310, 180, 14);

        jLabel49.setText(" ");
        jPanel9.add(jLabel49);
        jLabel49.setBounds(330, 310, 50, 30);

        jLabel50.setText("/");
        jPanel9.add(jLabel50);
        jLabel50.setBounds(380, 310, 10, 14);

        jLabel51.setText(" ");
        jPanel9.add(jLabel51);
        jLabel51.setBounds(400, 310, 110, 30);

        jLabel52.setText("Price: $");
        jPanel9.add(jLabel52);
        jLabel52.setBounds(140, 340, 90, 14);

        jLabel53.setText(" ");
        jPanel9.add(jLabel53);
        jLabel53.setBounds(200, 340, 160, 30);

        jLabel42.setText(" ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jPanel10);
        jPanel10.setBounds(160, 50, 190, 180);

        jButton32.setText("Ask for a Bite");
        jPanel9.add(jButton32);
        jButton32.setBounds(520, 410, 190, 50);

        jLabel54.setText("Send a short message:");
        jPanel9.add(jLabel54);
        jLabel54.setBounds(140, 400, 140, 40);

        jTextField7.setText(" ");
        jPanel9.add(jTextField7);
        jTextField7.setBounds(280, 410, 170, 50);

        jLabel55.setText("How many servings do you want?(Intergers only)");
        jPanel9.add(jLabel55);
        jLabel55.setBounds(140, 370, 290, 14);

        jTextField16.setText(" ");
        jPanel9.add(jTextField16);
        jTextField16.setBounds(430, 370, 50, 20);

        jLabel56.setText("City:");
        jPanel9.add(jLabel56);
        jLabel56.setBounds(140, 290, 23, 14);

        jLabel57.setText(" ");
        jPanel9.add(jLabel57);
        jLabel57.setBounds(170, 290, 90, 20);

        jLabel58.setText("Distance:");
        jPanel9.add(jLabel58);
        jLabel58.setBounds(330, 290, 80, 14);

        jLabel59.setText("  ");
        jPanel9.add(jLabel59);
        jLabel59.setBounds(410, 280, 80, 30);

        jLabel60.setText("miles away from you");
        jPanel9.add(jLabel60);
        jLabel60.setBounds(510, 290, 250, 14);

        javax.swing.GroupLayout f7Layout = new javax.swing.GroupLayout(f7.getContentPane());
        f7.getContentPane().setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));
        jPanel15.setLayout(null);

        jButton34.setText("Home");
        jPanel15.add(jButton34);
        jButton34.setBounds(10, 80, 100, 80);

        jButton35.setText("Notification");
        jPanel15.add(jButton35);
        jButton35.setBounds(10, 190, 100, 80);

        jButton36.setText("Account");
        jPanel15.add(jButton36);
        jButton36.setBounds(10, 300, 100, 80);

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel61.setText("Account Setting");
        jPanel15.add(jLabel61);
        jLabel61.setBounds(280, 40, 230, 40);

        jLabel62.setText(" ");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel16);
        jPanel16.setBounds(170, 90, 130, 100);

        jButton37.setText("Choose File...");
        jPanel15.add(jButton37);
        jButton37.setBounds(330, 100, 150, 30);

        jLabel63.setText("Username:");
        jPanel15.add(jLabel63);
        jLabel63.setBounds(330, 150, 90, 14);

        jLabel64.setText("Password:");
        jPanel15.add(jLabel64);
        jLabel64.setBounds(330, 180, 80, 14);

        jTextField17.setText(" ");
        jPanel15.add(jTextField17);
        jTextField17.setBounds(440, 150, 210, 20);

        jLabel65.setText("Phone Number:");
        jPanel15.add(jLabel65);
        jLabel65.setBounds(180, 220, 110, 14);

        jTextField18.setText(" ");
        jPanel15.add(jTextField18);
        jTextField18.setBounds(290, 220, 210, 20);
        jPanel15.add(jPasswordField1);
        jPasswordField1.setBounds(440, 180, 210, 20);

        jLabel66.setText("Gender(M/F/O):");
        jPanel15.add(jLabel66);
        jLabel66.setBounds(180, 260, 120, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel15.add(jComboBox1);
        jComboBox1.setBounds(290, 260, 64, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        jPanel15.add(jComboBox6);
        jComboBox6.setBounds(590, 260, 80, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel15.add(jComboBox7);
        jComboBox7.setBounds(460, 260, 45, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel15.add(jComboBox8);
        jComboBox8.setBounds(530, 260, 37, 20);

        jLabel67.setText("Birthday");
        jPanel15.add(jLabel67);
        jLabel67.setBounds(400, 260, 40, 14);

        jLabel68.setText("Bio:");
        jPanel15.add(jLabel68);
        jLabel68.setBounds(180, 300, 18, 14);

        jTextField2.setText(" ");
        jPanel15.add(jTextField2);
        jTextField2.setBounds(210, 300, 440, 90);

        jButton38.setText("Submit Changes");
        jPanel15.add(jButton38);
        jButton38.setBounds(560, 410, 160, 40);

        jButton39.setText("Cancel");
        jPanel15.add(jButton39);
        jButton39.setBounds(180, 410, 170, 40);

        javax.swing.GroupLayout fALayout = new javax.swing.GroupLayout(fA.getContentPane());
        fA.getContentPane().setLayout(fALayout);
        fALayout.setHorizontalGroup(
            fALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        fALayout.setVerticalGroup(
            fALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 204));
        jPanel17.setLayout(null);

        jButton41.setText("Home");
        jPanel17.add(jButton41);
        jButton41.setBounds(10, 80, 100, 80);

        jButton42.setText("Notification");
        jPanel17.add(jButton42);
        jButton42.setBounds(10, 190, 100, 80);

        jButton43.setText("Account");
        jPanel17.add(jButton43);
        jButton43.setBounds(10, 300, 100, 80);

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel69.setText("Notifications");
        jPanel17.add(jLabel69);
        jLabel69.setBounds(290, 30, 230, 40);

        Nameofevent.setText(" ");

        dropoutbutton.setText("Close");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Foodpic1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nameofevent, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dropoutbutton)
                        .addGap(37, 37, 37))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Foodpic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Nameofevent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(dropoutbutton)
                        .addGap(21, 21, 21))))
        );

        jPanel17.add(jPanel18);
        jPanel18.setBounds(160, 350, 540, 110);

        jScrollBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel17.add(jScrollBar2);
        jScrollBar2.setBounds(750, 90, 21, 390);

        Nameofevent1.setText(" ");

        time1.setText("Time:");

        address1.setText("Address:");

        dropoutbutton1.setText("Drop Out");

        timeforevent1.setText(" ");

        addressforevent1.setText(" ");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Foodpic2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nameofevent1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(time1)
                                .addGap(18, 18, 18)
                                .addComponent(timeforevent1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(address1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressforevent1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dropoutbutton1)
                        .addGap(39, 39, 39))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Foodpic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(Nameofevent1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeforevent1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(address1)
                                .addComponent(addressforevent1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dropoutbutton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel17.add(jPanel19);
        jPanel19.setBounds(160, 90, 540, 110);

        Nameofevent2.setText(" ");

        dropoutbutton2.setText("Close");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Foodpic3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nameofevent2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dropoutbutton2)
                        .addGap(40, 40, 40))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(Nameofevent2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(dropoutbutton2))
                    .addComponent(Foodpic3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel17.add(jPanel20);
        jPanel20.setBounds(160, 220, 540, 110);

        javax.swing.GroupLayout fNLayout = new javax.swing.GroupLayout(fN.getContentPane());
        fN.getContentPane().setLayout(fNLayout);
        fNLayout.setHorizontalGroup(
            fNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        fNLayout.setVerticalGroup(
            fNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 204));
        jPanel21.setLayout(null);

        jLabel70.setText(" ");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel21.add(jPanel22);
        jPanel22.setBounds(160, 50, 190, 180);

        jButton33.setText("Home");
        jPanel21.add(jButton33);
        jButton33.setBounds(10, 70, 100, 80);

        jButton40.setText("Notification");
        jPanel21.add(jButton40);
        jButton40.setBounds(10, 160, 100, 80);

        jButton44.setText("Account");
        jPanel21.add(jButton44);
        jButton44.setBounds(10, 250, 100, 80);

        jLabel71.setText("Name:");
        jPanel21.add(jLabel71);
        jLabel71.setBounds(390, 60, 38, 16);

        requestername.setText(" ");
        jPanel21.add(requestername);
        requestername.setBounds(450, 50, 250, 30);

        jLabel72.setText("Gender:");
        jPanel21.add(jLabel72);
        jLabel72.setBounds(390, 140, 46, 16);

        genderfhN.setText(" ");
        jPanel21.add(genderfhN);
        genderfhN.setBounds(460, 140, 190, 50);

        jButton5.setText("Come and Grab A Bite!");
        jPanel21.add(jButton5);
        jButton5.setBounds(500, 400, 220, 60);

        jButton10.setText("Oops, sorry!");
        jPanel21.add(jButton10);
        jButton10.setBounds(120, 400, 240, 60);

        javax.swing.GroupLayout fhNLayout = new javax.swing.GroupLayout(fhN.getContentPane());
        fhN.getContentPane().setLayout(fhNLayout);
        fhNLayout.setHorizontalGroup(
            fhNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        fhNLayout.setVerticalGroup(
            fhNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton21.setText("OK");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton21)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jButton21)
                .addGap(187, 187, 187))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String a = t1.getText();
        String b = new String(p1.getPassword());
        try
        {
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","Shruberry");
          Statement stmt = con.createStatement();
          String s = "select * from login where uid='"+a+"' and pass = '"+b+"';";
          ResultSet rs =stmt.executeQuery(s);
          if(rs.next())
          {
              JOptionPane.showMessageDialog(null,"boooo");
              f1.dispose();
              f3.setExtendedState(f1.getExtendedState()|NewJFrame.MAXIMIZED_BOTH);
              f3.setVisible(true);
          }
          else
          {
              JOptionPane.showMessageDialog(null,"wrong username or password, plz try again ");
              t1.setText("");
              p1.setText("");
          }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.dispose();
f1.setExtendedState(f1.getExtendedState()|NewJFrame.MAXIMIZED_BOTH);
f1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
f1.dispose();
f2.setExtendedState(f1.getExtendedState()|NewJFrame.MAXIMIZED_BOTH);
f2.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foodpic1;
    private javax.swing.JLabel Foodpic2;
    private javax.swing.JLabel Foodpic3;
    private javax.swing.JLabel Nameofevent;
    private javax.swing.JLabel Nameofevent1;
    private javax.swing.JLabel Nameofevent2;
    private javax.swing.JPanel PicofFood;
    private javax.swing.JLabel address1;
    private javax.swing.JLabel addressforevent1;
    private javax.swing.JButton dropoutbutton;
    private javax.swing.JButton dropoutbutton1;
    private javax.swing.JButton dropoutbutton2;
    private javax.swing.JFrame f1;
    private javax.swing.JFrame f2;
    private javax.swing.JFrame f3;
    private javax.swing.JFrame f4;
    private javax.swing.JFrame f5;
    private javax.swing.JFrame f6;
    private javax.swing.JFrame f7;
    private javax.swing.JFrame fA;
    private javax.swing.JFrame fN;
    private javax.swing.JFrame fhN;
    private javax.swing.JLabel genderfhN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPasswordField p1;
    private javax.swing.JLabel requestername;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel timeforevent1;
    private javax.swing.JButton uploadAPicture;
    // End of variables declaration//GEN-END:variables
}
